// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnt6vagvNFD8kODGjEI7CvkikV-bGQv-w',
    appId: '1:38517736356:web:707e2c74b3440cb905b731',
    messagingSenderId: '38517736356',
    projectId: 'souq-9ab11',
    authDomain: 'souq-9ab11.firebaseapp.com',
    databaseURL: 'https://souq-9ab11-default-rtdb.firebaseio.com',
    storageBucket: 'souq-9ab11.appspot.com',
    measurementId: 'G-GZJKW9QPLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsxJXiNFQB4QP_jwM8Nhzj4OJdNajJI18',
    appId: '1:38517736356:android:d00a91ab221871ea05b731',
    messagingSenderId: '38517736356',
    projectId: 'souq-9ab11',
    databaseURL: 'https://souq-9ab11-default-rtdb.firebaseio.com',
    storageBucket: 'souq-9ab11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChuzyVyUcXae49XPWXZxKoeYRkVltFsE4',
    appId: '1:38517736356:ios:ddb658d078cfb6b905b731',
    messagingSenderId: '38517736356',
    projectId: 'souq-9ab11',
    databaseURL: 'https://souq-9ab11-default-rtdb.firebaseio.com',
    storageBucket: 'souq-9ab11.appspot.com',
    androidClientId: '38517736356-5ku9socbnn2rkg63h8k72ef7qcsvlcak.apps.googleusercontent.com',
    iosClientId: '38517736356-tginkqv7r5qec9s2fcl6rum4nh8n6hqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.souq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChuzyVyUcXae49XPWXZxKoeYRkVltFsE4',
    appId: '1:38517736356:ios:ddb658d078cfb6b905b731',
    messagingSenderId: '38517736356',
    projectId: 'souq-9ab11',
    databaseURL: 'https://souq-9ab11-default-rtdb.firebaseio.com',
    storageBucket: 'souq-9ab11.appspot.com',
    androidClientId: '38517736356-5ku9socbnn2rkg63h8k72ef7qcsvlcak.apps.googleusercontent.com',
    iosClientId: '38517736356-tginkqv7r5qec9s2fcl6rum4nh8n6hqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.souq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnt6vagvNFD8kODGjEI7CvkikV-bGQv-w',
    appId: '1:38517736356:web:b71cdd6204860f7505b731',
    messagingSenderId: '38517736356',
    projectId: 'souq-9ab11',
    authDomain: 'souq-9ab11.firebaseapp.com',
    databaseURL: 'https://souq-9ab11-default-rtdb.firebaseio.com',
    storageBucket: 'souq-9ab11.appspot.com',
    measurementId: 'G-T1CLV56YS7',
  );

}